#!/bin/sh
### BEGIN INIT INFO
# Provides:          init_hdmi_audio
# Required-Start:
# Required-Stop:
# Default-Start: 2
# Default-Stop:
# Short-Description: Play dummy audio to initialize hdmi softvol
# Description:
### END INIT INFO
. /lib/lsb/init-functions
case "$1" in
  start)
    log_daemon_msg "Starting init_hdmi_audio"
    aplay -D sysdefault:vc4hdmi0 -d 1 -t raw -r 48000 -c 2 -f S16_LE /dev/zero &&
    update-rc.d init_hdmi_audio remove &&
    rm /etc/init.d/init_hdmi_audio &&
    log_end_msg $?
    ;;
  *)
    echo "Usage: $0 start" >&2
    exit 3
    ;;
esac