#!/bin/sh
### BEGIN INIT INFO
# Provides:          switch2ondem_cpugov
# Required-Start:
# Required-Stop:
# Default-Start: 2
# Default-Stop:
# Short-Description: Switch to ondemand cpu governor
# Description:
### END INIT INFO

. /lib/lsb/init-functions

case "$1" in
  start)
    log_daemon_msg "Switching to ondemand scaling governor"
    SYS_CPUFREQ_GOVERNOR=/sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
    if [ -e $SYS_CPUFREQ_GOVERNOR ]; then
    for cpu_core in /sys/devices/system/cpu/cpu?/cpufreq/scaling_governor ; do
        echo "ondemand" > $cpu_core
    done
    echo "50" > /sys/devices/system/cpu/cpufreq/ondemand/up_threshold
    echo "100000" > /sys/devices/system/cpu/cpufreq/ondemand/sampling_rate
    echo "50" > /sys/devices/system/cpu/cpufreq/ondemand/sampling_down_factor
    echo "0" > /sys/devices/system/cpu/cpufreq/ondemand/io_is_busy
    log_end_msg 0
    fi
    ;;
  stop)
    ;;
  restart)
    ;;
  force-reload)
    ;;
  *)
    echo "Usage: $0 start" >&2
    exit 3
    ;;
esac
